### ISSUE TITLE
Error: cannot import name lookitconfig

### ISSUE THREAD

**Issue by crittermike** [zachtib/lookit#14]
Lookit won't load for me since the last time it was updated from the PPA (a few weeks ago). When running "lookit" from the command line, I get this error:

```
Traceback (most recent call last):
  File "/usr/bin/lookit", line 47, in <module>
      from lookit import lookitconfig
```

Any idea? Googling didn't return a single result, so it appears I'm the only one who's having this problem.

**Comment by zachtib** [comment]
That was a problem with the beta2 package build (I forgot to update the MANIFEST, whoops) I just pushed a new package which should fix the issue.

**Comment by crittermike** [comment]
Just confirming that that fixed it. Thanks!
