### ISSUE TITLE
FTP upload crash. No error displayed

### ISSUE THREAD

**Issue by Bacteries** [zachtib/lookit#17]
Hi, I use lookit and It worked fine until last update.
Now when I try to take a capture I have an Error : "Error occured during FTP upload", but I don't know what happen.

I try to launch /usr/bin/lookit in a terminal and here is the trace (there is no message when I made a capture) :

ype gchararray to type GdkColor
  'gtk-icon-theme-name')
/usr/bin/lookit:79: Warning: g_value_unset: assertion `G_IS_VALUE (value)' failed
  'gtk-icon-theme-name')
/usr/bin/lookit:79: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint
  'gtk-icon-theme-name')
/usr/lib/pymodules/python2.6/lookit/data/pref.xml
/usr/lib/pymodules/python2.6/lookit/prefdlg.py:19: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  builder.add_from_file(xmlfile)
/usr/lib/pymodules/python2.6/lookit/prefdlg.py:52: RuntimeWarning: missing handler 'on_pref_dialog_close'
  builder.connect_signals(self)
<gtk.gdk.Event at 0x8e21050: GDK_LEAVE_NOTIFY x=-303,00, y=-319,00, mode=GDK_CROSSING_GRAB>

A bouton to test the FTP could be usefull.

Thanks.

**Comment by zachtib** [comment]
I've confirmed this issue on my end, looking into it now

**Comment by zachtib** [comment]
Ok, this should be fixed now, in both the 0.4 branch as well as the master branch, and will be included in 0.4.1 packages
