### ISSUE TITLE
Captured image is cropped

### ISSUE THREAD

**Issue by almozavr** [zachtib/lookit#18]
Selected area is always cropped by vertical: http://i.imgur.com/VkErF.png
Entire screen seems to be OK.

**Comment by zachtib** [comment]
What distro are you running? I'm also seeing this issue since upgrading to Natty. It looks like the image is captured ok, however, as the local copy is fine, but after upload, the same image is missing the bottom portion.

**Comment by almozavr** [comment]
I'm on Natty.

Also I found neither default Image Viewer or Shutter can't open local copy — maybe it's saved with damage. Shotwell opens it but yes, it's cropped: http://is.gd/zUSNvV

**Comment by zachtib** [comment]
Hrm, I _can_ open the local copy with Image Viewer and GIMP, and it seems fine. I'll take some more and see if there's any change

**Comment by lachesis** [comment]
I'm getting the same problem, also on Natty x64. When I try to open the image in feh, I get "libpng read error". Gimp gives a similar error. My images are all cropped by a few pixels from the bottom. 

Whole screen also works for me.

**Comment by zachtib** [comment]
Ok, it looks like the issue isn't related to the uploading process, so I'm about to look into the actual screencapping

**Comment by zachtib** [comment]
Fixed. The issue was that the temporary file was not being flushed and closed before upload
