### ISSUE TITLE
Capture active window via hotkey shortcut does not work

### ISSUE THREAD

**Issue by craige111** [zachtib/lookit#21]
If I press the <Ctrl><Super>3 or whatever I set it to, it doesn't take a screenshot of the active window as I would expect.

**Comment by craige111** [comment]
I am using the ppa:lookit/testing

**Comment by zachtib** [comment]
Yeah, hotkeys are broken in 1.0 right now, working on this for beta2

**Comment by craige111** [comment]
Thanks, but why put the option in before it is finished?

**Comment by zachtib** [comment]
It's left over from 0.4. Some of the changes in 1.0 broke the way hotkeys work and I didn't realize till after the first beta went out

**Comment by zachtib** [comment]
New hotkey code was just checked in

**Comment by craige111** [comment]
Will I get the fix when updating the PPA I am using  (ppa:lookit/testing)?

**Comment by zachtib** [comment]
you should, yes
