### ISSUE TITLE
Composited Selector doesn't work on Intel + Natty

### ISSUE THREAD

**Issue by zachtib** [zachtib/lookit#25]

**Comment by craige111** [comment]
Ok I tested the new Preference for Intel.  The problem with it is that the red border that appears does work, but due to a bug, the partial screenshot you get includes (you guessed it) the red border itself round the edge.  So we are getting there, but no cigar yet.

**Comment by zachtib** [comment]
Yeah, I see that behavior as well. Could you open a separate issue so I can
tag that on the next release?

On Mon, Jul 11, 2011 at 4:26 PM, craige111 <
reply@reply.github.com>wrote:

> Ok I tested the new Preference for Intel.  The problem with it is that the
> red border that appears does work, but due to a bug, the partial screenshot
> you get includes (you guessed it) the red border itself round the edge.  So
> we are getting there, but no cigar yet.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/issues/25#issuecomment-1549626

## 

Zach Tibbitts
