### ISSUE TITLE
How to replace panel icon?

### ISSUE THREAD

**Issue by crittermike** [zachtib/lookit#29]
Sorry, support request rather than bug report:

Is /usr/share/pixmaps/lookit.svg the file that I can replace to give Lookit a custom panel icon (on Ubuntu 11.04 so Unity if that matters)? Or another file somewhere?

**Comment by zachtib** [comment]
you want to change lookit-panel.svg, which is in one of:

/usr/share/icons/hicolor/scalable/apps/lookit-panel.svg
/usr/share/icons/ubuntu-mono-dark/apps/22/lookit-panel.svg
/usr/share/icons/ubuntu-mono-dark/apps/24/lookit-panel.svg
/usr/share/icons/ubuntu-mono-light/apps/22/lookit-panel.svg
/usr/share/icons/ubuntu-mono-light/apps/24/lookit-panel.svg

**Comment by crittermike** [comment]
Thanks! For others with the same question, changing /usr/share/icons/hicolor/scalable/apps/lookit-panel.svg worked for me.

**Comment by zachtib** [comment]
Glad you got that worked out. Although, in the next version (whether it's 1.2 or 2.0 I've yet to decide) The icons will be moving around a bit, as well as a new default icon

**Comment by crittermike** [comment]
Cool, I'll look forward to that then. For the record, here's the one I'm using so that it integrates well with Faenza: http://media.dropdo.com.s3.amazonaws.com/7hM/lookit.svg

Screenshot of panel: http://i.imgur.com/VMI3A.png
