### ISSUE TITLE
Indicator uses bad icon

### ISSUE THREAD

**Issue by syntax-zz** [zachtib/lookit#3]
Looking into the source code (file "lookit" from line 80), this is a known issue, I just want to point it out and discuss some solutions.

I have my own icon theme as a superset of "ubuntu-mono-dark"; Lookit checks only for the mentioned theme and then fallbacks to the default black icon, which is almost invisible on the dark panel.

Default icon should be visible on both dark and light foreground, since there are much more dark themes, so this is not an Ubuntu theming specific issue. Just add some white outline to the default icon and it should be fine.

About Ubuntu theming issue, most applications I have seen solves panel icon theming by installing their own icons into related directory in /usr/share/icons - this way, you can provide panel icons for other themes in future (like Elementary) and don't need to do the detection in code. See e.g. Shutter's package.

**Comment by zachtib** [comment]
Added a white border to the stock icon. I've tried getting properly themed icons to work but ran into some trouble, I'll take another look again soon, but I'm marking this closed for now

**Comment by almozavr** [comment]
The icon looks like lost on the dark panel.
