### ISSUE TITLE
Cancelling an area capture kills lookit

### ISSUE THREAD

**Issue by ghost** [zachtib/lookit#32]
OS: Ubuntu 11.04
Lookit: 1.1.0

When cancelling an area capture with esc, lookit crashes on my computer.

**Comment by zachtib** [comment]
Can you run Lookit in a terminal and give me the output when it crashes?
On Sep 6, 2011 5:52 AM, "cbrunos" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
I don't think there's anything relevant:

cbrunos@bamboo:~$ lookit
(7742)/kdeui (Wallet): The kwalletd service has been disabled
(7742)/kdeui (Wallet): The kwalletd service has been disabled
(7742)/kdeui (Wallet): The kwalletd service has been disabled
(7742)/kdeui (Wallet): The kwalletd service has been disabled
(7742)/kdeui (Wallet): The kwalletd service has been disabled
(7742)/kdeui (Wallet): The kwalletd service has been disabled
Ubuntu One support not found
cbrunos@bamboo:~$

On Tue, Sep 6, 2011 at 1:56 PM, zachtib <
reply@reply.github.com>wrote:

> Can you run Lookit in a terminal and give me the output when it crashes?
> On Sep 6, 2011 5:52 AM, "cbrunos" <
> reply@reply.github.com>
> wrote:
> 
> > OS: Ubuntu 11.04
> > Lookit: 1.1.0
> > 
> > When cancelling an area capture with esc, lookit crashes on my computer.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/zachtib/lookit/issues/32
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/issues/32#issuecomment-2014353

## 

## Rodrigues Bruno

http://cbrunos.wordpress.com
