### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by stas** [zachtib/lookit#36]
Hi,
can we get rid or relative imports from lookit module files?

It's a pain to develop against relative paths and there's no win at all preserving those.

**Comment by zachtib** [comment]
Which ones in particular do you mean? In the master branch right now, they're formatted as "from . import foo" is that what you're talking about? That was done automatically by the 2to3 script.

**Comment by stas** [comment]
Pe 13.09.2011 18:07, Zach Tibbitts a scris:

> Which ones in particular do you mean? In the master branch right now, they're formatted as "from . import foo" is that what you're talking about? That was done automatically by the 2to3 script.
> 
> Yep.
> I'm trying to set-up a development environment for lookit and didn't 
> find a solution to use the current imports as they are now.

Btw, may I ask  how did you set-up a dev-env to develop/test lookit?

**Comment by zachtib** [comment]
Well, those imports are the preferred syntax for Python 3. If you want to hack on Lookit, you might be better off pulling the 1.x branch. master is currently progress towards 2.0, and it's a big mess at the moment, I don't think any of it actually runs.

My dev env is just a Linux install with the required Python libraries. For 1.x that's pygtk, python-keybinder-gnome, python-notify, and probably a couple other things. 1.x was developed on Ubuntu, but I'm on Arch at the moment while working on 2.0

**Comment by stas** [comment]
Oky, thanks a lot.
That makes sense.
