### ISSUE TITLE
SSH public key support

### ISSUE THREAD

**Issue by vxnick** [zachtib/lookit#38]
Would it be possible to add this? Doesn't seem to detect/use mine.

**Comment by zachtib** [comment]
Yeah, it's something I'd like to implement. AFAIK, the library I'm using for
ssh supports it, I just need to enable the functionality

On Fri, Oct 14, 2011 at 9:50 AM, Nick Trew <
reply@reply.github.com>wrote:

> Would it be possible to add this? Doesn't seem to detect/use mine.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/issues/38

## 

Zach Tibbitts

**Comment by vxnick** [comment]
I'll have a go at implementing this later and will send over a pull request if I manage to get it working :-)

**Comment by zachtib** [comment]
Sounds good!
On Oct 14, 2011 10:23 AM, "Nick Trew" <
reply@reply.github.com>
wrote:
