### ISSUE TITLE
Daily Builds PPA

### ISSUE THREAD

**Issue by stas** [zachtib/lookit#42]
Hey Zach,
do you mind setting up a mirror for this github repo on launchpad to set up a daily builder?

Check this
https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted#Setting_up_the_recipe_in_Launchpad

Thanks in advance.

**Comment by zachtib** [comment]
I'll look into this later today. I got my virtual ubuntu env set up, and
have what appears to be a working source package for 1.2. I'm hoping to get
it uploaded to the testing ppa today.

On Mon, Oct 17, 2011 at 7:16 AM, Stas Sușcov <
reply@reply.github.com>wrote:

> Hey Zach,
> do you mind setting up a mirror for this github repo on launchpad to set up
> a daily builder?
> 
> Check this
> 
> https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted#Setting_up_the_recipe_in_Launchpad
> 
> Thanks in advance.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/issues/42

## 

Zach Tibbitts

**Comment by stas** [comment]
On Lu 17 oct 2011 14:47:07 +0300, Zach Tibbitts wrote:

> I'll look into this later today. I got my virtual ubuntu env set up, and
> have what appears to be a working source package for 1.2. I'm hoping to get
> it uploaded to the testing ppa today.
> 
> On Mon, Oct 17, 2011 at 7:16 AM, Stas Sușcov<
> reply@reply.github.com>wrote:
> 
> > Hey Zach,
> > do you mind setting up a mirror for this github repo on launchpad to set up
> > a daily builder?
> > 
> > Check this
> > 
> > https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted#Setting_up_the_recipe_in_Launchpad
> > 
> > Thanks in advance.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/zachtib/lookit/issues/42

Nice.
In fact, if you could setup a mirror, I can try setting up a daily 
builder for that.
Thanks.

**Comment by stas** [comment]
PPA works fine.
https://launchpad.net/~lookit/+archive/daily
