### ISSUE TITLE
Lookit updates aren't being pushed to Lookit Testing PPA

### ISSUE THREAD

**Issue by thomasboxley** [zachtib/lookit#45]
The recent updates to lookit haven't been pushed to the Lookit Testing PPA. In fact, the stable PPA is even more updated than the testing one. Please consider updating the Testing PPA more.

**Comment by zachtib** [comment]
If you're familiar with the PPA system, would you be interested in helping maintain it? I don't use Ubuntu anymore, so I keep forgetting to update it. If you're interested, I can give you access to the PPA

**Comment by stas** [comment]
Hey, if @tboxley has no time, I can pickup this task.
My Launchpad profile is
https://launchpad.net/~sushkov

Hope we can fix this asap.

**Comment by zachtib** [comment]
@stas ok, you should have upload access now

**Comment by stas** [comment]
On Lu 05 dec 2011 16:28:52 +0200, Zach Tibbitts wrote:

> @stas ok, you should have upload access now

Thanks. I will take a look asap.

**Comment by stas** [comment]
Okey,
I set up a mirror
https://code.launchpad.net/~lookit/lookit/mirror
and a recipe that will use this branch (which we probably should merge into the github codebase)
https://code.launchpad.net/~lookit/+recipe/lookit-daily

Lets see if it builds ok.
If not, we'll tweak it.

**Comment by stas** [comment]
Works for me :)
Closing this.

sudo apt-add-repository ppa:lookit/daily

**Comment by thomasboxley** [comment]
On 12/05/2011 11:38 AM, Stas Sușcov wrote:

> Works for me :)
> Closing this.
> 
> sudo apt-add-repository ppa:lookit/daily
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/issues/45#issuecomment-3020130

This is brilliant. Thank you very much!

## 

Thanks,
Thomas Boxley
http://thomasboxley.com
