### ISSUE TITLE
Ubuntu 14.04 (Trusty) PPA support

### ISSUE THREAD

**Issue by Dirrot** [zachtib/lookit#58]
Is it possible to provide a package for Ubuntu 14.04 (Trusty) via ppa?

**Comment by Dirrot** [comment]
.done

**Comment by Dirrot** [comment]
wrong repo :D

**Comment by sashasimkin** [comment]
I can't install :-( It says "No package available".

P.s: Used instruction in README(ppa:lookit/daily)

**Comment by Dirrot** [comment]
Thats right, currently there is no package for trusty. Within the next 10-14 days i'm going to change that.

**Comment by sashasimkin** [comment]
Thank you! Will wait for that.

**Comment by Dirrot** [comment]
really .done

**Comment by sashasimkin** [comment]
Same result as previously:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty
```
