### ISSUE TITLE
Get cloud app support

### ISSUE THREAD

**Issue by jakegissing** [zachtib/lookit#6]
I love this tool, by far my favourite screenshot tool, and I've recently found a great app called getcloudapp.com

I would love to be able to upload my images there with Lookit.

I did some research for you, and there's a python wrapper on github for Cloud App.

I hope you can develop this feature! :)

**Comment by jakegissing** [comment]
Sorry forgot to include the wrapper link

http://github.com/originell/pycloudapp

**Comment by zachtib** [comment]
Done, and it will be in 1.0!

**Comment by jakegissing** [comment]
Thank you!
